// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeS8nPaBOZkWuPzfKhZGBbh1TZIDHL0nY',
    appId: '1:619409461810:web:25b25fce54fa93bc1ca22b',
    messagingSenderId: '619409461810',
    projectId: 'bank-crashlycts',
    authDomain: 'bank-crashlycts.firebaseapp.com',
    storageBucket: 'bank-crashlycts.appspot.com',
    measurementId: 'G-30Q1X0V3R9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgtV7nT5fK0l8mKHDBhqne7C-HYx_9dvE',
    appId: '1:619409461810:android:2f104daecad53dd91ca22b',
    messagingSenderId: '619409461810',
    projectId: 'bank-crashlycts',
    storageBucket: 'bank-crashlycts.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm0eh_T7N3c7X99VbAgFJOo_ZzcfMOPBg',
    appId: '1:619409461810:ios:88adfa22fdb71e811ca22b',
    messagingSenderId: '619409461810',
    projectId: 'bank-crashlycts',
    storageBucket: 'bank-crashlycts.appspot.com',
    iosClientId: '619409461810-3669m9qm2u4hj7jhn53equ8tl1q7fi6u.apps.googleusercontent.com',
    iosBundleId: 'com.example.bytebank2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm0eh_T7N3c7X99VbAgFJOo_ZzcfMOPBg',
    appId: '1:619409461810:ios:88adfa22fdb71e811ca22b',
    messagingSenderId: '619409461810',
    projectId: 'bank-crashlycts',
    storageBucket: 'bank-crashlycts.appspot.com',
    iosClientId: '619409461810-3669m9qm2u4hj7jhn53equ8tl1q7fi6u.apps.googleusercontent.com',
    iosBundleId: 'com.example.bytebank2',
  );
}
